apiVersion: v1
kind: PersistentVolume
metadata:
  name: "wordpress-fn-pv"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/fn/wp
    server: nfs.xxx.xxx